create table if not exists public.system_states (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.insights (
  id bigint generated by default as identity primary key,
  tweet_id text not null unique,
  author_handle text not null,
  author_name text,
  tweet_text text not null,
  tweet_url text not null,
  tweet_created_at timestamptz,
  impact_score int not null check (impact_score between 1 and 10),
  target_sectors text[] not null default '{}',
  summary_zh text not null,
  trading_action text not null,
  original_zh text,
  why_it_matters_zh text,
  market_mechanism_zh text,
  affected_tickers text[] not null default '{}',
  confidence_score int check (confidence_score between 1 and 10),
  time_horizon text,
  source_quality text,
  risk_zh text,
  inserted_at timestamptz not null default now()
);

alter table public.insights
  add column if not exists original_zh text,
  add column if not exists why_it_matters_zh text,
  add column if not exists market_mechanism_zh text,
  add column if not exists affected_tickers text[] not null default '{}',
  add column if not exists confidence_score int check (confidence_score between 1 and 10),
  add column if not exists time_horizon text,
  add column if not exists source_quality text,
  add column if not exists risk_zh text;

create index if not exists insights_inserted_at_idx
  on public.insights (inserted_at desc);

create index if not exists insights_impact_score_idx
  on public.insights (impact_score desc);

create index if not exists insights_affected_tickers_idx
  on public.insights using gin (affected_tickers);

create index if not exists insights_confidence_score_idx
  on public.insights (confidence_score desc);


create table if not exists public.event_clusters (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  title text not null,
  summary_zh text not null,
  why_it_matters_zh text,
  market_mechanism_zh text,
  trading_action text,
  risk_zh text,
  impact_max int not null check (impact_max between 1 and 10),
  confidence_avg numeric(4,2),
  confidence_max int check (confidence_max between 1 and 10),
  source_quality text,
  time_horizon text,
  tickers text[] not null default '{}',
  sectors text[] not null default '{}',
  tweet_ids text[] not null default '{}',
  source_handles text[] not null default '{}',
  source_tweet_urls text[] not null default '{}',
  source_count int not null default 0,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_tweet_created_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists event_clusters_last_seen_at_idx
  on public.event_clusters (last_seen_at desc);

create index if not exists event_clusters_impact_idx
  on public.event_clusters (impact_max desc, confidence_max desc);

create index if not exists event_clusters_tickers_idx
  on public.event_clusters using gin (tickers);

create index if not exists event_clusters_sectors_idx
  on public.event_clusters using gin (sectors);


create table if not exists public.tweet_queue (
  tweet_id text primary key,
  tweet_id_int numeric(20,0) not null default 0,
  author_handle text not null,
  author_name text,
  tweet_text text not null,
  tweet_url text not null,
  tweet_created_at timestamptz,
  author_followers bigint,
  source text not null default 'x',
  status text not null default 'pending' check (status in ('pending', 'processed', 'failed')),
  attempts int not null default 0,
  last_error text,
  priority_score int not null default 0,
  priority_reason text[] not null default '{}',
  is_stale boolean not null default false,
  stale_processed_at timestamptz,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.tweet_queue
  add column if not exists priority_score int not null default 0,
  add column if not exists priority_reason text[] not null default '{}',
  add column if not exists is_stale boolean not null default false,
  add column if not exists stale_processed_at timestamptz;

create index if not exists tweet_queue_pending_idx
  on public.tweet_queue (status, attempts, priority_score desc, tweet_id_int desc);

create index if not exists tweet_queue_priority_idx
  on public.tweet_queue (status, priority_score desc, tweet_id_int desc)
  where status = 'pending';

create index if not exists tweet_queue_inserted_at_idx
  on public.tweet_queue (inserted_at desc);

create table if not exists public.telegram_alerts (
  id bigint generated by default as identity primary key,
  alert_type text not null,
  session_id text,
  period_start timestamptz,
  period_end timestamptz,
  title text not null,
  message_html text not null,
  message_markdown text not null,
  insight_ids text[] not null default '{}',
  source_tweet_urls text[] not null default '{}',
  impact_max int check (impact_max between 1 and 10),
  confidence_avg numeric(4,2),
  tickers text[] not null default '{}',
  sectors text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.daily_study_briefs (
  id bigint generated by default as identity primary key,
  study_date date not null unique,
  timezone text not null default 'Asia/Hong_Kong',
  title text not null,
  brief_markdown text not null,
  alert_ids bigint[] not null default '{}',
  tickers text[] not null default '{}',
  sectors text[] not null default '{}',
  source_tweet_urls text[] not null default '{}',
  alert_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_alerts_created_at_idx
  on public.telegram_alerts (created_at desc);

create index if not exists telegram_alerts_session_id_idx
  on public.telegram_alerts (session_id);

create index if not exists telegram_alerts_tickers_idx
  on public.telegram_alerts using gin (tickers);

create index if not exists daily_study_briefs_study_date_idx
  on public.daily_study_briefs (study_date desc);

insert into public.system_states (key, value)
values ('last_processed_tweet_id', '0')
on conflict (key) do nothing;

alter table public.system_states enable row level security;
alter table public.insights enable row level security;
alter table public.event_clusters enable row level security;
alter table public.tweet_queue enable row level security;
alter table public.telegram_alerts enable row level security;
alter table public.daily_study_briefs enable row level security;

drop policy if exists "public read insights" on public.insights;
create policy "public read insights"
  on public.insights
  for select
  using (true);

drop policy if exists "public read event clusters" on public.event_clusters;
create policy "public read event clusters"
  on public.event_clusters
  for select
  using (true);


drop policy if exists "public read telegram alerts" on public.telegram_alerts;
create policy "public read telegram alerts"
  on public.telegram_alerts
  for select
  using (true);

drop policy if exists "public read daily study briefs" on public.daily_study_briefs;
create policy "public read daily study briefs"
  on public.daily_study_briefs
  for select
  using (true);

-- Do not create public write policies. The crawler should use a Supabase
-- service-role key via GitHub Secrets.
