create table if not exists public.system_states (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.insights (
  id bigint generated by default as identity primary key,
  tweet_id text not null unique,
  author_handle text not null,
  author_name text,
  tweet_text text not null,
  tweet_url text not null,
  tweet_created_at timestamptz,
  impact_score int not null check (impact_score between 1 and 10),
  target_sectors text[] not null default '{}',
  summary_zh text not null,
  trading_action text not null,
  inserted_at timestamptz not null default now()
);

create index if not exists insights_inserted_at_idx
  on public.insights (inserted_at desc);

create index if not exists insights_impact_score_idx
  on public.insights (impact_score desc);

insert into public.system_states (key, value)
values ('last_processed_tweet_id', '0')
on conflict (key) do nothing;

alter table public.system_states enable row level security;
alter table public.insights enable row level security;

drop policy if exists "public read insights" on public.insights;
create policy "public read insights"
  on public.insights
  for select
  using (true);

-- Do not create public write policies. The crawler should use a Supabase
-- service-role key via GitHub Secrets.
